# Generated by Django 5.2 on 2026-03-06 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('drag_and_drop', 'Glisser-deposer'), ('matching', 'Appariement'), ('fill_in_blank', 'Texte a trous'), ('true_false', 'Vrai ou Faux'), ('ordering', 'Mise en ordre'), ('custom_react', 'Composant React personnalise')], max_length=30)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text="Configuration JSON de l'activite. Structure depend du type.")),
                ('react_component_url', models.URLField(blank=True, help_text='URL du composant React (pour le type custom_react uniquement)')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Activite interactive',
                'verbose_name_plural': 'Activites interactives',
                'db_table': 'activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoursePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(help_text='URL du fichier PDF (S3 ou autre)', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Support de cours (PDF)',
                'verbose_name_plural': 'Supports de cours (PDF)',
                'db_table': 'course_pdfs',
                'ordering': ['order'],
            },
        ),
    ]
