# Generated by Django 5.2 on 2026-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_activity_coursepdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('drag_and_drop', 'Glisser-deposer'), ('matching', 'Appariement'), ('fill_in_blank', 'Texte a trous'), ('true_false', 'Vrai ou Faux'), ('ordering', 'Mise en ordre'), ('custom_react', 'Composant React personnalise'), ('simulator', 'Simulateur interactif')], max_length=30),
        ),
    ]
