# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('activity', 'Activite interactive'), ('text', 'Texte / Lecture')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_gating', models.BooleanField(default=True, help_text='Must complete to unlock next section')),
                ('vdocipher_id', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('quiz_data', models.JSONField(blank=True, null=True)),
                ('pass_score', models.IntegerField(default=70)),
                ('activity_type', models.CharField(blank=True, choices=[('drag_and_drop', 'Glisser-deposer'), ('matching', 'Associations'), ('fill_in_blank', 'Texte a trous'), ('true_false', 'Vrai ou Faux'), ('ordering', 'Mise en ordre'), ('multiple_choice', 'Choix multiple'), ('labeling', 'Etiquetage'), ('flashcards', 'Cartes memoire'), ('classification', 'Classification'), ('simulator', 'Simulateur')], max_length=30)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.chapter')),
            ],
            options={
                'db_table': 'chapter_sections',
                'ordering': ['chapter', 'order'],
            },
        ),
    ]
