import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(...parts: string[]) {
  return readFileSync(join(process.cwd(), ...parts), 'utf8').replace(/\r\n?/g, '\n')
}

describe('professor surface polish', () => {
  it('keeps the professor mobile nav accessible and self-closing', () => {
    const navSource = source('components', 'professor', 'ProfessorTopNav.tsx')

    expect(navSource).toContain('aria-label="Professor workspace"')
    expect(navSource).toContain('aria-label={menuOpen ? \'Close navigation\' : \'Open navigation\'}')
    expect(navSource).toContain('aria-expanded={menuOpen}')
    expect(navSource).toContain('aria-controls="professor-mobile-menu"')
    expect(navSource).toContain('id="professor-mobile-menu"')
    expect(navSource).toContain('setMenuOpen(false)\n  }, [pathname])')
    expect(navSource).toContain('const professorUnreadMessagesHref = `${AUTH_ROUTES.professorChat}?filter=unread`')
    expect(navSource).toContain('href={professorUnreadMessagesHref}')
    expect(navSource).toContain('aria-label="Open unread professor messages"')
    expect(navSource).toContain('<span aria-hidden="true" className="absolute right-3 top-3 h-2 w-2 rounded-full bg-[#f5900b]" />')
  })

  it('keeps professor login readiness and errors accessible', () => {
    const loginSource = source('app', 'professor', 'login', 'page.tsx')

    expect(loginSource).toContain('const normalizedEmail = email.trim().toLowerCase()')
    expect(loginSource).toContain('const hasCredentials = normalizedEmail.length > 0 && password.length > 0')
    expect(loginSource).toContain('const canSubmit = hasCredentials && !loading')
    expect(loginSource).toContain("const professorLoginFieldDescription = `professor-login-help${error ? ' professor-login-error' : ''}`")
    expect(loginSource).toContain('function updateEmail(value: string)')
    expect(loginSource).toContain('function updatePassword(value: string)')
    expect(loginSource).toContain("if (error) setError('')")
    expect(loginSource).toContain("setError('Renseignez email professeur et mot de passe.')")
    expect(loginSource).toContain('getFirebaseEmailPasswordIdToken(normalizedEmail, password)')
    expect(loginSource).toContain('aria-describedby={professorLoginFieldDescription}')
    expect(loginSource).toContain('aria-label="Professor login requirements"')
    expect(loginSource).toContain('id="professor-login-help"')
    expect(loginSource).toContain('id="professor-login-error"')
    expect(loginSource).toContain('disabled={!canSubmit}')
  })

  it('keeps professor dashboard compact and tied to actionable surfaces', () => {
    const dashboardSource = source('app', 'professor', 'page.tsx')

    expect(dashboardSource).toContain('const dashboardRiskRadar = buildDashboardRiskRadar({')
    expect(dashboardSource).toContain('const dashboardPriorityRows = dashboardRiskRadar.slice(0, 3)')
    expect(dashboardSource).toContain('aria-label="Professor dashboard overview"')
    expect(dashboardSource).toContain('function DashboardMetricCard({')
    expect(dashboardSource).toContain('function DashboardQueueRow({ item }: { item: DashboardRiskRadarItem })')
    expect(dashboardSource).toContain('function buildDashboardRiskRadar({')
    expect(dashboardSource).toContain("'Live setup': { href: liveHref, action: 'Open live' }")
    expect(dashboardSource).toContain("'Student replies': { href: chatHref, action: 'Open inbox' }")
    expect(dashboardSource).toContain("'Studio review': { href: reviewHref, action: 'Open review' }")
    expect(dashboardSource).toContain("'Course context': { href: studioHref, action: 'Open Studio' }")
    expect(dashboardSource).toContain('.sort((left, right) => left.score - right.score)')
  })

  it('keeps live scheduling stable on mobile and validates time ranges', () => {
    const liveSource = source('app', 'professor', 'live', 'page.tsx')

    expect(liveSource).toContain('if (endsAt <= startsAt)')
    expect(liveSource).toContain('toast.error(\'End time must be after the start time.\')')
    expect(liveSource).toContain('sm:grid-cols-2')
    expect(liveSource).toContain('aria-controls="professor-live-advanced-fields"')
    expect(liveSource).toContain('lg:sticky lg:top-24')
    expect(liveSource).toContain('break-all text-[12px] font-bold text-[#3f3f46]')
  })

  it('keeps live sessions easy to triage by status and stream readiness', () => {
    const liveSource = source('app', 'professor', 'live', 'page.tsx')

    expect(liveSource).toContain("import { usePathname, useRouter, useSearchParams } from 'next/navigation'")
    expect(liveSource).toContain('const LIVE_STATUS_FILTER_VALUES = new Set<LiveStatusFilter>(LIVE_STATUS_FILTERS.map((filter) => filter.value))')
    expect(liveSource).toContain("const routeStatus = useMemo(() => normalizeLiveStatus(new URLSearchParams(searchKey).get('status')), [searchKey])")
    expect(liveSource).toContain("const routeSearch = useMemo(() => new URLSearchParams(searchKey).get('q')?.trim() ?? '', [searchKey])")
    expect(liveSource).toContain('const [statusFilter, setStatusFilter] = useState<LiveStatusFilter>(routeStatus)')
    expect(liveSource).toContain('const [liveSearch, setLiveSearch] = useState(routeSearch)')
    expect(liveSource).toContain('function replaceLiveUrlState(nextStatus: LiveStatusFilter, nextSearch: string)')
    expect(liveSource).toContain('router.replace(queryString ? `${pathname}?${queryString}` : pathname, { scroll: false })')
    expect(liveSource).toContain('function selectLiveStatus(nextStatus: LiveStatusFilter)')
    expect(liveSource).toContain('function updateLiveSearch(value: string)')
    expect(liveSource).toContain('function clearLiveSearch()')
    expect(liveSource).toContain('function normalizeLiveStatus(value: string | null | undefined): LiveStatusFilter')
    expect(liveSource).toContain("const filteredSessions = useMemo(() => (")
    expect(liveSource).toContain("statusFilter === 'all' ? sortedSessions : sortedSessions.filter((session) => session.status === statusFilter)")
    expect(liveSource).toContain('const normalizedLiveSearch = liveSearch.trim().toLowerCase()')
    expect(liveSource).toContain('const visibleSessions = useMemo(() => (')
    expect(liveSource).toContain('liveSessionMatchesSearch(session, normalizedLiveSearch)')
    expect(liveSource).toContain('aria-label="Live session controls"')
    expect(liveSource).toContain('aria-label="Search live sessions"')
    expect(liveSource).toContain('aria-label="Clear live session search"')
    expect(liveSource).toContain('aria-label="Live session filters"')
    expect(liveSource).toContain('aria-label="Live session summary"')
    expect(liveSource).toContain('<LiveMetric label="Live"')
    expect(liveSource).toContain('<LiveMetric label="Scheduled"')
    expect(liveSource).toContain('<LiveMetric label="Ready"')
    expect(liveSource).toContain('No matching live sessions')
    expect(liveSource).toContain('Clear search')
    expect(liveSource).toContain('visibleSessions.map((session) =>')
    expect(liveSource).toContain('function liveSessionMatchesSearch(session: ProfessorLiveSession, query: string)')
    expect(liveSource).toContain('onChange={(event) => updateLiveSearch(event.target.value)}')
    expect(liveSource).toContain('onClick={clearLiveSearch}')
    expect(liveSource).toContain('onClick={() => selectLiveStatus(filter.value)}')
    expect(liveSource).toContain("onClick={() => selectLiveStatus('all')}")
    expect(liveSource).toContain('formRef.current?.scrollIntoView({ behavior: \'smooth\', block: \'start\' })')
    expect(liveSource).toContain('aria-label="Revealed stream credentials"')
    expect(liveSource).toContain('<LiveCredentialRow label="OBS URL" value={revealedCredentials.stream_ingest_url} />')
    expect(liveSource).toContain('<LiveCredentialRow label="Stream key" value={revealedCredentials.stream_key} />')
    expect(liveSource).toContain('function LiveCredentialRow({ label, value }: { label: string; value: string })')
    expect(liveSource).toContain('onClick={() => void copyLiveCredential(label, value)}')
    expect(liveSource).toContain('aria-label={`Copy ${label}`}')
    expect(liveSource).toContain('async function copyLiveCredential(label: string, value: string)')
    expect(liveSource).toContain('navigator.clipboard.writeText(trimmed)')
    expect(liveSource).toContain('toast.success(`${label} copied.`)')
    expect(liveSource).toContain('function liveSessionChecklist(session: ProfessorLiveSession): LiveReadinessItem[]')
    expect(liveSource).toContain('function ReadinessPill({ item }: { item: LiveReadinessItem })')
    expect(liveSource).toContain('isLiveNotificationSent(session.notification_status)')
    expect(liveSource).toContain('aria-label={`${session.title} readiness`}')
    expect(liveSource).toContain('function duplicateLiveSession(session: ProfessorLiveSession)')
    expect(liveSource).toContain('setForm(duplicateFormFromSession(session))')
    expect(liveSource).toContain('formRef.current?.scrollIntoView({ behavior: \'smooth\', block: \'start\' })')
    expect(liveSource).toContain('onDuplicate={() => duplicateLiveSession(session)}')
    expect(liveSource).toContain('Duplicate schedule')
    expect(liveSource).toContain('function duplicateFormFromSession(session: ProfessorLiveSession): LiveForm')
    expect(liveSource).toContain('const durationMs = Math.max(30 * 60 * 1000, sourceEnd.getTime() - sourceStart.getTime())')
    expect(liveSource).toContain("vdocipher_live_id: ''")
    expect(liveSource).toContain("stream_ingest_url: ''")
    expect(liveSource).toContain("stream_key: ''")
    expect(liveSource).toContain('function nextRecurringSessionStart(sourceStart: Date)')
    expect(liveSource).not.toContain('<LiveRunbookPanel')
    expect(liveSource).not.toContain('aria-label="Active live readiness checklist"')
    expect(liveSource).not.toContain('function ReadinessCheck({ item }: { item: LiveReadinessItem })')
  })

  it('keeps the control room desktop-height behavior off mobile', () => {
    const controlSource = source('app', 'professor', 'live', '[sessionId]', 'page.tsx')

    expect(controlSource).toContain('const hasStreamCredentials = Boolean(session?.has_stream_credentials)')
    expect(controlSource).toContain("const answeredCount = questions.filter((item) => item.status === 'answered').length")
    expect(controlSource).toContain("type QuestionQueueFilter = 'all' | 'pending' | 'answered'")
    expect(controlSource).toContain("type LiveControlPanel = 'question' | 'message'")
    expect(controlSource).toContain('const QUESTION_QUEUE_FILTERS')
    expect(controlSource).toContain('const QUESTION_QUEUE_FILTER_VALUES = new Set<QuestionQueueFilter>(QUESTION_QUEUE_FILTERS.map((filter) => filter.value))')
    expect(controlSource).toContain("const LIVE_CONTROL_PANEL_VALUES = new Set<LiveControlPanel>(['question', 'message'])")
    expect(controlSource).toContain("import { useParams, usePathname, useRouter, useSearchParams } from 'next/navigation'")
    expect(controlSource).toContain("const routePanel = useMemo(() => normalizeLiveControlPanel(new URLSearchParams(searchKey).get('panel')), [searchKey])")
    expect(controlSource).toContain("const routeQuestionFilter = useMemo(() => normalizeQuestionQueueFilter(new URLSearchParams(searchKey).get('filter')), [searchKey])")
    expect(controlSource).toContain("const routeRoomSearch = useMemo(() => new URLSearchParams(searchKey).get('q')?.trim() ?? '', [searchKey])")
    expect(controlSource).toContain('const [activePanel, setActivePanel] = useState<LiveControlPanel>(routePanel)')
    expect(controlSource).toContain('const [questionFilter, setQuestionFilter] = useState<QuestionQueueFilter>(routeQuestionFilter)')
    expect(controlSource).toContain('const [roomSearch, setRoomSearch] = useState(routeRoomSearch)')
    expect(controlSource).toContain('function replaceControlRoomUrlState(nextPanel: LiveControlPanel, nextFilter: QuestionQueueFilter, nextSearch: string)')
    expect(controlSource).toContain('router.replace(queryString ? `${pathname}?${queryString}` : pathname, { scroll: false })')
    expect(controlSource).toContain('function selectControlPanel(nextPanel: LiveControlPanel)')
    expect(controlSource).toContain('function selectQuestionFilter(nextFilter: QuestionQueueFilter)')
    expect(controlSource).toContain('function updateRoomSearch(value: string)')
    expect(controlSource).toContain('function clearRoomSearch()')
    expect(controlSource).toContain('function reviewQuestionQueue()')
    expect(controlSource).toContain('function normalizeLiveControlPanel(value: string | null | undefined): LiveControlPanel')
    expect(controlSource).toContain('function normalizeQuestionQueueFilter(value: string | null | undefined): QuestionQueueFilter')
    expect(controlSource).toContain('const filteredQuestions = useMemo(() => (')
    expect(controlSource).toContain('questions.filter((item) => item.status === questionFilter)')
    expect(controlSource).toContain('const normalizedRoomSearch = roomSearch.trim().toLowerCase()')
    expect(controlSource).toContain('const visibleQuestions = useMemo(() => (')
    expect(controlSource).toContain('filteredQuestions.filter((item) => liveRoomInteractionMatchesSearch(item, normalizedRoomSearch))')
    expect(controlSource).toContain('const visibleChatMessages = useMemo(() => (')
    expect(controlSource).toContain('chatMessages.filter((item) => liveRoomInteractionMatchesSearch(item, normalizedRoomSearch))')
    expect(controlSource).toContain('const activeItems = activePanel === \'question\' ? visibleQuestions : visibleChatMessages')
    expect(controlSource).toContain('const activePanelSourceCount = activePanel === \'question\' ? filteredQuestions.length : chatMessages.length')
    expect(controlSource).toContain('onClick={reviewQuestionQueue}')
    expect(controlSource).toContain("onClick={() => selectControlPanel('message')}")
    expect(controlSource).toContain('onClick={() => selectControlPanel(kind)}')
    expect(controlSource).toContain('onClick={() => selectQuestionFilter(filter.value)}')
    expect(controlSource).toContain('onChange={(event) => updateRoomSearch(event.target.value)}')
    expect(controlSource).toContain('onClick={clearRoomSearch}')
    expect(controlSource).toContain('aria-label="Question queue filters"')
    expect(controlSource).toContain('aria-label="Search live room interactions"')
    expect(controlSource).toContain('aria-label="Search live room"')
    expect(controlSource).toContain('aria-label="Clear live room search"')
    expect(controlSource).toContain('No matching live room items')
    expect(controlSource).toContain('Clear live room search')
    expect(controlSource).toContain('function liveRoomInteractionMatchesSearch(interaction: LiveSessionInteraction, query: string)')
    expect(controlSource).toContain("onClick={() => selectQuestionFilter('all')}")
    expect(controlSource).toContain('function emptyQuestionTitle(filter: QuestionQueueFilter)')
    expect(controlSource).toContain('const [answerDrafts, setAnswerDrafts] = useState<Record<number, string>>({})')
    expect(controlSource).toContain('function answerDraftFor(interaction: LiveSessionInteraction)')
    expect(controlSource).toContain('async function copyControlCredential(label: string, value: string)')
    expect(controlSource).toContain('navigator.clipboard.writeText(trimmed)')
    expect(controlSource).toContain('toast.success(`${label} copied.`)')
    expect(controlSource).toContain('<LiveControlCredentialRow label="OBS URL" value={streamCredentials.stream_ingest_url} onCopy={copyControlCredential} />')
    expect(controlSource).toContain('<LiveControlCredentialRow label="Stream key" value={streamCredentials.stream_key} onCopy={copyControlCredential} />')
    expect(controlSource).toContain('function LiveControlCredentialRow({')
    expect(controlSource).toContain('aria-label={`Copy control room ${label}`}')
    expect(controlSource).toContain('onClick={() => void onCopy(label, value)}')
    expect(controlSource).toContain('async function saveQuestionAnswer(interaction: LiveSessionInteraction)')
    expect(controlSource).toContain('const saved = await runInteractionAction(')
    expect(controlSource).toContain('if (!saved) return')
    expect(controlSource).toContain("patchProfessorLiveInteraction(interaction.id, { answer, status: 'answered' })")
    expect(controlSource).toContain('aria-label={`Answer question ${interaction.id}`}')
    expect(controlSource).toContain('Answer this question')
    expect(controlSource).toContain('Saved answer')
    expect(controlSource).toContain('disabled={busyId === interaction.id || !draftAnswer.trim()}')
    expect(controlSource).toContain('aria-label="Live control summary"')
    expect(controlSource).toContain('<LiveControlStatusPill label="Broadcast"')
    expect(controlSource).toContain('<LiveControlStatusPill label="Player"')
    expect(controlSource).toContain('<LiveControlStatusPill label="Stream"')
    expect(controlSource).toContain('<LiveControlStatusPill label="Questions"')
    expect(controlSource).toContain('{answeredCount} answered / {messageCount} chat')
    expect(controlSource).toContain("const nextFilter = pendingCount > 0 ? 'pending' : 'all'")
    expect(controlSource).toContain('function LiveControlStatusPill({')
    expect(controlSource).not.toContain('aria-label="Live operator brief"')
    expect(controlSource).not.toContain('function LiveBriefStep(')
    expect(controlSource).not.toContain('function buildLiveControlBrief(')
    expect(controlSource).not.toContain('type LiveControlBriefStep')
    expect(controlSource).not.toContain('<LiveControlMetric')
    expect(controlSource).toContain('xl:h-[calc(100vh-145px)] xl:min-h-[720px]')
    expect(controlSource).toContain('min-h-[260px] overflow-hidden')
    expect(controlSource).toContain('xl:h-full xl:min-h-0')
    expect(controlSource).not.toContain('!session?.has_stream_credentials ? <div /> : null')
    expect(controlSource).not.toContain('grid h-[calc(100vh-165px)] min-h-[720px]')
  })

  it('keeps professor change requests retryable inline', () => {
    const changesSource = source('app', 'professor', 'changes', 'page.tsx')

    expect(changesSource).toContain("const [loadError, setLoadError] = useState('')")
    expect(changesSource).toContain('apiDataErrorMessage(error, \'Impossible de charger les demandes.\')')
    expect(changesSource).toContain('aria-label="Chargement des demandes"')
    expect(changesSource).toContain('role="alert"')
    expect(changesSource).toContain('onClick={reload}')
    expect(changesSource).toContain("import { usePathname, useRouter, useSearchParams } from 'next/navigation'")
    expect(changesSource).toContain('const CHANGE_FILTER_VALUES = new Set(FILTERS.map((filter) => filter.value))')
    expect(changesSource).toContain("const routeStatus = useMemo(() => normalizeChangeStatus(new URLSearchParams(searchKey).get('status')), [searchKey])")
    expect(changesSource).toContain("const routeSearch = useMemo(() => new URLSearchParams(searchKey).get('q')?.trim() ?? '', [searchKey])")
    expect(changesSource).toContain('function replaceChangeRequestUrlState(nextStatus: string, nextSearch: string)')
    expect(changesSource).toContain("if (normalizedStatus === 'all') params.delete('status')")
    expect(changesSource).toContain("if (normalizedSearch) params.set('q', normalizedSearch)")
    expect(changesSource).toContain('router.replace(queryString ? `${pathname}?${queryString}` : pathname, { scroll: false })')
    expect(changesSource).toContain('function selectStatus(nextStatus: string)')
    expect(changesSource).toContain('function updateChangeSearch(value: string)')
    expect(changesSource).toContain('function clearChangeSearch()')
    expect(changesSource).toContain('setStatus((current) => (current === routeStatus ? current : routeStatus))')
    expect(changesSource).toContain('function normalizeChangeStatus(value: string | null | undefined)')
    expect(changesSource).toContain('const [status, setStatus] = useState(routeStatus)')
    expect(changesSource).toContain('const [changeSearch, setChangeSearch] = useState(routeSearch)')
    expect(changesSource).toContain('const visibleRequests = useMemo(() => (')
    expect(changesSource).toContain('changeRequestMatchesSearch(request, normalizedChangeSearch)')
    expect(changesSource).toContain('const queueStats = useMemo(() => buildChangeQueueStats(visibleRequests), [visibleRequests])')
    expect(changesSource).toContain('aria-label="Change request controls"')
    expect(changesSource).toContain('role="tablist" aria-label="Change request status filters"')
    expect(changesSource).toContain('aria-label="Search change requests"')
    expect(changesSource).toContain('aria-label="Clear change request search"')
    expect(changesSource).toContain('aria-label="Change request summary"')
    expect(changesSource).toContain('<QueueStat label="Requests" value={visibleRequests.length} />')
    expect(changesSource).toContain('<QueueStat label="Operations" value={queueStats.operations} />')
    expect(changesSource).toContain('<QueueStat label="Pending" value={queueStats.pending} tone="attention" />')
    expect(changesSource).toContain('aria-label="Change request queue"')
    expect(changesSource).toContain('function ChangeRequestRow({')
    expect(changesSource).toContain('function QueueStat({')
    expect(changesSource).toContain('function buildChangeQueueStats(requests: ProfessorChangeSummary[])')
    expect(changesSource).toContain('No matching requests')
    expect(changesSource).toContain('Clear search')
    expect(changesSource).toContain('visibleRequests.map((request) =>')
    expect(changesSource).toContain('function changeRequestMatchesSearch(request: ProfessorChangeSummary, query: string)')
    expect(changesSource).toContain('View all requests')
    expect(changesSource).toContain('function changeRequestProgress(request: ProfessorChangeSummary)')
    expect(changesSource).toContain('aria-label={`Progression demande ${request.id}`}')
    expect(changesSource).toContain('role="progressbar"')
    expect(changesSource).toContain('aria-valuenow={progress.percent}')
    expect(changesSource).toContain('Reviewed')
    expect(changesSource).toContain('function changeRequestAction(request: ProfessorChangeSummary)')
    expect(changesSource).toContain("cta: 'Edit'")
    expect(changesSource).toContain("cta: 'Revise'")
    expect(changesSource).toContain("cta: 'Inspect'")
    expect(changesSource).toContain('href: `/professor/studio?request=${request.id}`')
    expect(changesSource).toContain('href: `/professor/studio?offering=${request.course_offering_id}`')
    expect(changesSource).toContain('Cancel')
  })

  it('keeps professor chat triage visible and selected-thread context actionable', () => {
    const chatSource = source('app', 'professor', 'chat', 'page.tsx')

    expect(chatSource).toContain('const visibleUnreadCount = conversations.reduce')
    expect(chatSource).toContain("import { useSWRConfig } from 'swr'")
    expect(chatSource).toContain('const { mutate: mutateSWRCache } = useSWRConfig()')
    expect(chatSource).toContain('const prefetchedConversationIdsRef = useRef(new Set<number>())')
    expect(chatSource).toContain('professorMessagesSWRKey(conversationId)')
    expect(chatSource).toContain('const prefetchedMessages = await listProfessorMessages(conversationId)')
    expect(chatSource).toContain('function professorConversationButtonLabel(conversation: ProfessorConversation)')
    expect(chatSource).toContain('aria-label="Inbox triage"')
    expect(chatSource).toContain('<InboxMetric label="Visible" value={conversations.length} />')
    expect(chatSource).toContain('<InboxMetric label="Unread" value={visibleUnreadCount}')
    expect(chatSource).toContain('const activeNeedsReply = (active?.unread_for_professor ?? 0) > 0')
    expect(chatSource).toContain('{activeNeedsReply ? `${active.unread_for_professor} unread` : \'Up to date\'}')
    expect(chatSource).toContain('Latest: {activeLastMessage}')
    expect(chatSource).toContain("const [threadSearch, setThreadSearch] = useState('')")
    expect(chatSource).toContain('const normalizedThreadSearch = threadSearch.trim().toLowerCase()')
    expect(chatSource).toContain('const threadSearchMatches = useMemo(() => (')
    expect(chatSource).toContain('professorMessageMatchesThreadSearch(message, normalizedThreadSearch)')
    expect(chatSource).toContain('const renderedThreadMessages = hasThreadSearch ? threadSearchMatches : messageWindow.messages')
    expect(chatSource).toContain('aria-label="Active thread tools"')
    expect(chatSource).toContain('aria-label="Search active thread"')
    expect(chatSource).toContain('aria-label="Search messages in this thread"')
    expect(chatSource).toContain('aria-label="Clear thread search"')
    expect(chatSource).toContain('{hasThreadSearch && <span className="ml-2 font-black text-[#453dee]">{threadSearchMatches.length} match{threadSearchMatches.length === 1 ? \'\' : \'es\'}</span>}')
    expect(chatSource).toContain('No messages match this search.')
    expect(chatSource).toContain('renderedThreadMessages.map((message, visibleIndex) =>')
    expect(chatSource).toContain('function professorMessageMatchesThreadSearch(message: ProfessorMessage, query: string)')
    expect(chatSource).toContain('function focusReplyComposer()')
    expect(chatSource).toContain('draftTextareaRef.current?.focus()')
    expect(chatSource).toContain('Reply now')
    expect(chatSource).toContain('const [markingReadId, setMarkingReadId] = useState<number | null>(null)')
    expect(chatSource).toContain('async function markConversationRead(conversation: ProfessorConversation)')
    expect(chatSource).toContain('patchProfessorConversation(conversation.id, { mark_read: true })')
    expect(chatSource).toContain('updateProfessorConversationReadState(current, updated.id)')
    expect(chatSource).toContain('Mark read')
    expect(chatSource).toContain('const selectConversation = useCallback((conversation: ProfessorConversation) =>')
    expect(chatSource).toContain('prefetchConversationMessages(conversation.id)')
    expect(chatSource).toContain('onMouseEnter={() => prefetchConversationMessages(conversation.id)}')
    expect(chatSource).toContain('onFocus={() => prefetchConversationMessages(conversation.id)}')
    expect(chatSource).toContain('onClick={() => selectConversation(conversation)}')
    expect(chatSource).toContain('aria-label={professorConversationButtonLabel(conversation)}')
    expect(chatSource).not.toContain('<ProfessorThreadBrief items={activeThreadBrief} />')
    expect(chatSource).not.toContain('aria-label="Active student brief"')
    expect(chatSource).not.toContain('function buildProfessorThreadBrief(')
    expect(chatSource).not.toContain('VIP private thread')
  })

  it('keeps the professor studio editable on mobile', () => {
    const studioSource = source('components', 'professor', 'studio', 'StudioBoard.tsx')
    const opsTraySource = source('components', 'professor', 'studio', 'OpsTray.tsx')

    expect(studioSource).toContain('min-h-[calc(100svh-4rem)]')
    expect(studioSource).toContain('lg:h-[calc(100vh-4rem)]')
    expect(studioSource).toContain('{working.length} chapitre{working.length === 1 ? \'\' : \'s\'} · {operations.length} modification{operations.length === 1 ? \'\' : \'s\'} · {selectionLabel}')
    expect(studioSource).toContain('<span className={`rounded-full px-2.5 py-1 text-[11px] font-black uppercase tracking-[0.08em] ${readinessTone}`}>{readinessStatus}</span>')
    expect(studioSource).not.toContain('<StudioMetric label="Structure"')
    expect(studioSource).not.toContain('function StudioMetric(')
    expect(studioSource).toContain('className="min-h-[460px] overflow-hidden rounded-[16px] border border-[#e4e4e7] bg-white lg:hidden"')
    expect(studioSource.match(/<Inspector/g)?.length).toBeGreaterThanOrEqual(2)
    expect(studioSource).toContain('function duplicateSelected()')
    expect(studioSource).toContain('function cloneChapter(chapter: WorkChapter): WorkChapter')
    expect(studioSource).toContain("key: nextKey('chapter')")
    expect(studioSource).toContain('onDuplicate={duplicateSelected}')
    expect(studioSource).toContain('withdrawStudioChange')
    expect(studioSource).toContain('function withdrawPendingRequest()')
    expect(studioSource).toContain('original.pending_request_id != null')
    expect(studioSource).toContain('Annuler la demande')
    expect(studioSource).toContain('function restoreStudioDraft()')
    expect(studioSource).toContain("window.confirm(restoringEdit ? 'Restaurer la demande en attente ?' : 'Annuler les changements non soumis ?')")
    expect(studioSource).toContain('setWorking(restoringEdit ? projectOperations(tree, editOps) : treeToWorking(tree))')
    expect(studioSource).toContain('if (!restoringEdit) setSummary(\'\')')
    expect(studioSource).toContain("toast.success(restoringEdit ? 'Demande restauree.' : 'Brouillon annule.')")
    expect(studioSource).toContain("aria-label={editId != null ? 'Restaurer la demande en attente' : 'Annuler le brouillon Studio'}")
    expect(studioSource).toContain('onClick={() => void restoreStudioDraft()}')
    expect(studioSource).toContain('Annuler brouillon')
    expect(studioSource).toContain('Restaurer la demande')
    expect(studioSource).toContain('type StudioOperation')
    expect(studioSource).toContain('const operationSummary = useMemo(() => summarizeStudioOperations(operations), [operations])')
    expect(studioSource).toContain('aria-label="Studio submission bar"')
    expect(studioSource).toContain('Draft')
    expect(studioSource).toContain('No draft changes')
    expect(studioSource).toContain('operation${operations.length === 1 ? \'\' : \'s\'} ready')
    expect(studioSource).toContain('<StudioReviewPill label="create"')
    expect(studioSource).toContain('function summarizeStudioOperations(operations: StudioOperation[])')
    expect(studioSource).toContain('const studioReadiness = useMemo(() => collectStudioReadiness(working), [working])')
    expect(studioSource).toContain("import { usePathname, useRouter, useSearchParams } from 'next/navigation'")
    expect(studioSource).toContain('const router = useRouter()')
    expect(studioSource).toContain('const pathname = usePathname()')
    expect(studioSource).toContain('const searchParams = useSearchParams()')
    expect(studioSource).toContain('const searchKey = searchParams.toString()')
    expect(studioSource).toContain("const routeRequestId = useMemo(() => parseStudioRouteId(new URLSearchParams(searchKey).get('request')), [searchKey])")
    expect(studioSource).toContain("const routeOfferingId = useMemo(() => parseStudioRouteId(new URLSearchParams(searchKey).get('offering')), [searchKey])")
    expect(studioSource).toContain("const routeStudioSearch = useMemo(() => new URLSearchParams(searchKey).get('q')?.trim() ?? '', [searchKey])")
    expect(studioSource).toContain("const routeStudioSelection = useMemo(() => parseStudioSelection(new URLSearchParams(searchKey).get('selection')), [searchKey])")
    expect(studioSource).toContain('const [offeringId, setOfferingId] = useState<number | null>(routeOfferingId)')
    expect(studioSource).toContain('const [sel, setSel] = useState<Sel>(routeStudioSelection)')
    expect(studioSource).toContain('const [studioSearch, setStudioSearch] = useState(routeStudioSearch)')
    expect(studioSource).toContain('function syncStudioRoute()')
    expect(studioSource).toContain('getStudioChangeRequest(routeRequestId)')
    expect(studioSource).toContain('setStudioSearch((current) => (current === routeStudioSearch ? current : routeStudioSearch))')
    expect(studioSource).toContain('function replaceStudioUrlState(')
    expect(studioSource).toContain('router.replace(queryString ? `${pathname}?${queryString}` : pathname, { scroll: false })')
    expect(studioSource).toContain('function selectOffering(nextOfferingId: number)')
    expect(studioSource).toContain('function selectStudioSelection(nextSelection: Sel)')
    expect(studioSource).toContain('function updateStudioSearch(value: string)')
    expect(studioSource).toContain('function clearStudioSearch()')
    expect(studioSource).toContain('parseStudioSelection(new URLSearchParams(searchKey).get(\'selection\'))')
    expect(studioSource).toContain('const normalizedStudioSearch = studioSearch.trim().toLowerCase()')
    expect(studioSource).toContain('const studioSearchResults = useMemo(')
    expect(studioSource).toContain('collectStudioSearchResults(working, normalizedStudioSearch)')
    expect(studioSource).toContain('setStudioSearch(\'\')')
    expect(studioSource).toContain('aria-label="Studio structure search"')
    expect(studioSource).toContain('aria-label="Search studio structure"')
    expect(studioSource).toContain('aria-label="Clear studio structure search"')
    expect(studioSource).toContain('aria-label="Studio structure search results"')
    expect(studioSource).toContain('studioSearchResults.slice(0, 6).map((result) =>')
    expect(studioSource).toContain('onClick={() => focusStudioSearchResult(result)}')
    expect(studioSource).toContain('Aucun resultat dans la structure chargee.')
    expect(studioSource).toContain('function focusStudioSearchResult(result: StudioSearchResult)')
    expect(studioSource).toContain('if (result.chapterKey) setExpandedChapters((current) => new Set(current).add(result.chapterKey!))')
    expect(studioSource).toContain('if (result.lessonKey) setExpandedLessons((current) => new Set(current).add(result.lessonKey!))')
    expect(studioSource).toContain('selectStudioSelection(result.target)')
    expect(studioSource).toContain('function expandStudioTree()')
    expect(studioSource).toContain('setExpandedChapters(new Set(working.map((chapter) => chapter.key)))')
    expect(studioSource).toContain('setExpandedLessons(new Set(working.flatMap((chapter) => chapter.lessons.map((lesson) => lesson.key))))')
    expect(studioSource).toContain('function collapseStudioTree()')
    expect(studioSource).toContain('aria-label="Developper toute la structure"')
    expect(studioSource).toContain('aria-label="Replier toute la structure"')
    expect(studioSource).toContain('Tout ouvrir')
    expect(studioSource).toContain('Tout fermer')
    expect(studioSource).toContain('type StudioSearchResult')
    expect(studioSource).toContain('function collectStudioSearchResults(chapters: WorkChapter[], query: string): StudioSearchResult[]')
    expect(studioSource).toContain('function studioSearchText(values: Array<string | null | undefined>)')
    expect(studioSource).toContain('aria-label="Studio readiness summary"')
    expect(studioSource).toContain('function StudioReadinessSummary({')
    expect(studioSource).toContain('onIssueSelect: (issue: StudioReadinessIssue) => void')
    expect(studioSource).toContain('function collectStudioReadiness(chapters: WorkChapter[]): StudioReadiness')
    expect(studioSource).toContain('studioReadiness.blockers.length > 0')
    expect(studioSource).toContain('disabled={operations.length === 0 || submitting || studioReadiness.blockers.length > 0}')
    expect(studioSource).toContain('function focusReadinessIssue(issue: StudioReadinessIssue)')
    expect(studioSource).toContain('if (!issue.target) {')
    expect(studioSource).toContain('addChapter()')
    expect(studioSource).toContain('setExpandedChapters((current) => new Set(current).add(issue.chapterKey!))')
    expect(studioSource).toContain('setExpandedLessons((current) => new Set(current).add(issue.lessonKey!))')
    expect(studioSource).toContain('<StudioReadinessSummary readiness={studioReadiness} onIssueSelect={focusReadinessIssue} />')
    expect(studioSource).toContain('<OpsTray operations={operations} onOperationSelect={focusOperation} />')
    expect(studioSource).toContain('function focusOperation(operation: StudioOperation)')
    expect(studioSource).toContain('const target = selectionFromOperation(operation, working)')
    expect(studioSource).toContain('selectStudioSelection(target.selection)')
    expect(studioSource).toContain('This operation targets an item that is no longer in the draft tree.')
    expect(studioSource).toContain('function selectionFromOperation(operation: StudioOperation, chapters: WorkChapter[]): OperationTarget | null')
    expect(studioSource).toContain("selection: { type: 'chapter', key: chapter.key }")
    expect(studioSource).toContain("selection: { type: 'lesson', key: lesson.key }")
    expect(studioSource).toContain("selection: { type: 'tab', key: tab.key }")
    expect(studioSource).toContain('function StudioReadinessIssueCard({')
    expect(studioSource).toContain('onClick={() => onSelect(issue)}')
    expect(studioSource).toContain("const actionText = issue.target ? 'Open in inspector' : 'Add chapter'")
    expect(studioSource).toContain('target: { type: \'chapter\', key: chapter.key }')
    expect(studioSource).toContain('target: { type: \'lesson\', key: lesson.key }')
    expect(studioSource).toContain('target: { type: \'tab\', key: tab.key }')
    expect(studioSource).toContain('Chapter title is required.')
    expect(studioSource).toContain('Resource URL is required.')
    expect(studioSource).toContain('Choose a simulator for this lab tab.')
    expect(studioSource).toContain('function parseStudioRouteId(value: string | null | undefined)')
    expect(studioSource).toContain('function parseStudioSelection(value: string | null | undefined): Sel')
    expect(studioSource).toContain('function serializeStudioSelection(selection: Sel)')
    expect(studioSource).toContain('function sameStudioSelection(left: Sel, right: Sel)')
    expect(studioSource).toContain('function selectionFromRoute(selection: NonNullable<Sel>, chapters: WorkChapter[]): OperationTarget | null')
    expect(studioSource).toContain("onChange={(e) => selectOffering(Number(e.target.value))}")
    expect(studioSource).toContain('onChange={(event) => updateStudioSearch(event.target.value)}')
    expect(studioSource).toContain('onClick={clearStudioSearch}')
    expect(studioSource).toContain("onClick={() => selectStudioSelection({ type: 'chapter', key: chapter.key })}")
    expect(studioSource).toContain("onClick={() => selectStudioSelection({ type: 'lesson', key: lesson.key })}")
    expect(studioSource).toContain("onClick={() => selectStudioSelection({ type: 'tab', key: tab.key })}")
    expect(opsTraySource).toContain('onOperationSelect?: (operation: StudioOperation) => void')
    expect(opsTraySource).toContain('aria-label={`Inspect operation ${i + 1}`}')
    expect(opsTraySource).toContain('onClick={() => onOperationSelect?.(op)}')
    expect(opsTraySource).toContain('Inspect')
  })

  it('keeps professor studio simulator tabs configurable from the catalog', () => {
    const inspectorSource = source('components', 'professor', 'studio', 'Inspector.tsx')

    expect(inspectorSource).toContain('defaultConfigFor, findSimulator, type SimulatorParam')
    expect(inspectorSource).toContain('function SimulatorParamField')
    expect(inspectorSource).toContain("const selectedSimulator = type === 'tab' && node.tab_type === 'lab'")
    expect(inspectorSource).toContain('selectedSimulator.params.map((param) =>')
    expect(inspectorSource).toContain('value={node.config[param.key]}')
    expect(inspectorSource).toContain('onChange={(value) => onChange({ config: { ...node.config, [param.key]: value } })}')
    expect(inspectorSource).toContain("onSelect={(key) => onChange({ renderer_key: key, tab_type: 'lab', config: defaultConfigFor(key) })}")
    expect(inspectorSource).toContain('onDuplicate: () => void')
    expect(inspectorSource).toContain('aria-label="Dupliquer la selection"')
  })

  it('keeps professor studio simulator library selectable on mobile', () => {
    const librarySource = source('components', 'professor', 'studio', 'SimulatorLibrary.tsx')

    expect(librarySource).toContain('function selectSimulator(key: string)')
    expect(librarySource).toContain('className="relative border-b border-[#f4f4f5] px-5 py-2.5 sm:hidden"')
    expect(librarySource).toContain('aria-pressed={isFocused}')
    expect(librarySource).toContain('onDoubleClick={() => selectSimulator(sim.key)}')
    expect(librarySource).toContain('aria-label={`Choisir ${sim.title}`}')
    expect(librarySource).toContain("{isCurrent ? 'Actif' : 'Choisir'}")
    expect(librarySource).toContain('onClick={() => { if (focusedSim) selectSimulator(focusedSim.key) }}')
  })
})
