# Generated by Django 5.2 on 2026-03-07 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_quizresult_userxp_videoquiztrigger_xptransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('complete_lesson', 'Complete a lesson'), ('pass_quiz', 'Pass a quiz'), ('study_minutes', 'Study for X minutes'), ('earn_xp', 'Earn X XP')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('target', models.IntegerField(default=1)),
                ('progress', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=25)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_quests',
                'unique_together': {('user', 'quest_type', 'date')},
            },
        ),
    ]
