# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_dailyquest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='item_type',
            field=models.CharField(choices=[('block', 'Block'), ('quiz', 'Quiz'), ('section', 'Section')], max_length=20),
        ),
    ]
