import asyncio
from pathlib import Path

import pytest

import app.dependencies as dependencies


class _FakeSession:
    def __init__(self):
        self.rollback_calls = 0

    async def rollback(self):
        self.rollback_calls += 1


class _FakeFactoryContext:
    def __init__(self, session: _FakeSession):
        self._session = session

    async def __aenter__(self):
        return self._session

    async def __aexit__(self, exc_type, exc, tb):
        del exc_type, exc, tb
        return False


def _install_factory(monkeypatch, session: _FakeSession):
    monkeypatch.setattr(dependencies, "get_session_factory", lambda: lambda: _FakeFactoryContext(session))


@pytest.mark.parametrize("exc_type", [asyncio.CancelledError, KeyboardInterrupt])
def test_get_db_rolls_back_on_base_exception_and_re_raises(monkeypatch, exc_type):
    session = _FakeSession()
    _install_factory(monkeypatch, session)

    async def _exercise():
        agen = dependencies.get_db(None)
        yielded = await agen.__anext__()
        assert yielded is session
        with pytest.raises(exc_type):
            await agen.athrow(exc_type())

    asyncio.run(_exercise())

    assert session.rollback_calls == 1


def test_get_db_does_not_rollback_on_normal_exit(monkeypatch):
    session = _FakeSession()
    _install_factory(monkeypatch, session)

    async def _exercise():
        async for yielded in dependencies.get_db(None):
            assert yielded is session

    asyncio.run(_exercise())

    assert session.rollback_calls == 0


def test_backend_dependency_lock_is_hash_pinned():
    backend_dir = Path(__file__).resolve().parents[1]
    requirements_in = backend_dir / "requirements.in"
    requirements_txt = backend_dir / "requirements.txt"

    requirements_in_text = requirements_in.read_text(encoding="utf-8")
    requirements_txt_text = requirements_txt.read_text(encoding="utf-8")

    assert requirements_in.exists()
    assert requirements_txt.exists()
    assert requirements_in_text.strip() != ""
    assert requirements_txt_text.startswith("#\n# This file is autogenerated by pip-compile")
    assert "--hash=sha256:" in requirements_txt_text
    assert "pip-compile --generate-hashes" in requirements_txt_text
