export const DEFAULT_LOCALE = 'fr-MA'

export const localizedCopy = {
  auth: {
    welcome: 'Bienvenue sur Kresco',
    loginToAccess: 'Connectez-vous pour accéder à vos cours.',
    continueWithGoogle: 'Continuer avec Google',
    facebookComingSoon: 'Facebook (bientôt)',
    appleComingSoon: 'Apple (bientôt)',
    loginLoading: 'Connexion...',
    createAccount: 'Créer un compte',
    alreadyHaveAccount: 'Déjà un compte ?',
    loginAction: 'Se connecter',
    signUpTitle: 'Inscription',
    joinFree: 'Rejoignez Kresco gratuitement.',
    fullName: 'Nom complet',
    fullNamePlaceholder: 'Ahmed Benali',
    email: 'Email',
    emailPlaceholder: 'vous@exemple.com',
    password: 'Mot de passe',
    passwordMinPlaceholder: 'Min. 8 caracteres',
    passwordPlaceholder: 'Votre mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    createAccountAction: 'Créer mon compte',
    creating: 'Création...',
    noAccountYet: 'Pas encore de compte ?',
    verifyEmailTitle: 'Vérifiez votre email',
    verifyEmailBody1: 'Nous avons envoyé un lien à',
    verifyEmailBody2: 'Cliquez dessus pour activer votre compte.',
    resendEmail: "Renvoyer l'email",
    resending: 'Envoi...',
    backToHome: "Retour à l'accueil",
    logInTitle: 'Connexion',
    welcomeBack: 'Content de vous revoir !',
    forgotPassword: 'Mot de passe oublié ?',
    forgotPasswordTitle: 'Mot de passe oublié',
    forgotPasswordBody: 'Entrez votre email, nous vous enverrons un lien de réinitialisation.',
    sendLink: 'Envoyer le lien',
    backToLogin: 'Retour à la connexion',
    emailSentTitle: 'Email envoyé !',
    emailSentBody: 'Si un compte existe avec cette adresse, vous recevrez un lien sous peu.',
    whatLevel: 'Quel est votre niveau ?',
    helpsUsPersonalize: 'Cela nous aide à personnaliser votre expérience.',
    continueBtn: 'Continuer',
    whatSpecialty: 'Quelle est votre filière ?',
    selectSpecialty: 'Sélectionnez votre spécialité.',
    start: 'Commencer',
    saving: 'Sauvegarde...',
    loading: 'Chargement...',
    google: 'Google',
    facebook: 'Facebook',
    apple: 'Apple',
    or: 'ou',
    termsSummary: 'En utilisant Kresco, vous acceptez nos conditions et notre politique de confidentialité.',
    resetPasswordInvalidLinkTitle: 'Lien invalide',
    resetPasswordInvalidLinkBody: 'Ce lien de réinitialisation est invalide ou a expiré.',
    resetPasswordSuccessTitle: 'Mot de passe mis à jour !',
    resetPasswordSuccessBody: 'Redirection vers la connexion...',
    resetPasswordTitle: 'Nouveau mot de passe',
    resetPasswordBody: 'Choisissez un mot de passe sécurisé pour votre compte.',
    resetPasswordConfirmLabel: 'Confirmer le mot de passe',
    resetPasswordConfirmPlaceholder: 'Répétez le mot de passe',
    resetPasswordSaveBtn: 'Enregistrer le mot de passe',
    resetPasswordMismatch: 'Les mots de passe ne correspondent pas',
    verifyEmailVerifiedTitle: 'Email vérifié !',
    verifyEmailVerifiedBody: 'Votre adresse a été confirmée avec succès.',
    verifyEmailChecking: 'Vérification en cours...',
    verifyEmailInvalidTitle: 'Lien invalide',
    verifyEmailInvalidBody: 'Ce lien de vérification est invalide ou a expiré.',
    verifyEmailFailedTitle: 'Vérification échouée',
    professorLoginTitle: 'Espace Professeur',
    professorLoginBody: 'Connectez-vous pour gérer vos cours et interagir avec les élèves.',
    professorLoginAction: 'Connexion Professeur',
    professorBadge: 'Professeur',
    professorEmailPlaceholder: 'professeur@kresco.ma',
    professorOnlyError: 'Cette connexion est réservée aux comptes professeur.',
    professorLoginFailed: 'Connexion impossible.',
    verifyEmailBeforeLogin: 'Vérifiez votre email avant de vous connecter.',
  },

  pricing: {
    backHome: "Retour a l'accueil",
    badge: 'Ameliorez votre apprentissage',
    title: 'Tarification simple et transparente',
    subtitle: 'Un paiement unique pour debloquer Kresco Pro.',
    freePlan: 'Gratuit',
    freePrice: '0 MAD',
    freeDescription: 'Commencez avec les lecons en apercu.',
    previousPlan: 'Plan precedent',
    currentPlan: 'Plan actuel',
    proPlan: 'Pro',
    popular: 'Le plus populaire',
    proPrice: '99 MAD',
    oneTime: 'une fois',
    paymentActivation: 'Acces Pro active apres confirmation du paiement.',
    proDescription: "Tout ce qu'il faut pour progresser.",
    proActive: 'Vous etes Pro !',
    checkout: "Acheter l'acces Pro - 99 MAD",
    creatingPayment: 'Preparation du paiement...',
    securePayment: 'Paiement unique avec confirmation securisee',
    supportTitle: 'Paiement non lance',
    supportBody: 'Vous pouvez reessayer ou contacter le support avec la methode choisie. Si vous avez deja paye, gardez votre recu.',
    supportMethod: 'Methode',
    supportRetry: 'Reessayer',
    supportContact: 'Contacter le support',
    paymentStatusPendingProvider: 'Paiement carte en attente de confirmation. Si vous avez deja paye, contactez le support avec votre reference.',
    paymentStatusFailed: 'La derniere tentative de paiement a echoue. Vous pouvez reessayer ou contacter le support avec votre reference.',
    paymentStatusMismatch: 'Le paiement ne correspond pas encore a la demande attendue. Contactez le support avec votre recu.',
    paymentStatusExpired: 'Cette demande de paiement a expire. Vous pouvez creer une nouvelle demande.',
    paymentStatusNeedsReview: 'Cette demande de paiement necessite une verification avant activation.',
    pendingToast: 'Demande de paiement creee.',
    pendingTitle: 'Paiement en attente',
    pendingReference: 'Reference',
    pendingAmount: 'Montant',
    proofReference: 'Reference du recu',
    proofReferencePlaceholder: 'Ex: CASH-123456 ou VIR-001',
    proofPayerName: 'Nom du payeur',
    proofPayerNamePlaceholder: 'Nom sur le recu',
    proofUrl: 'Lien du justificatif',
    proofUrlPlaceholder: 'Lien Drive, image ou PDF',
    proofNotes: 'Note',
    proofNotesPlaceholder: 'Banque, agence, date ou precision utile',
    proofSubmit: 'Envoyer le justificatif',
    proofSubmitting: 'Envoi...',
    proofRequired: 'Ajoutez une reference ou un lien de justificatif.',
    proofSubmitted: 'Justificatif envoye.',
    proofSubmittedStatus: 'Justificatif recu. Access active apres verification finance.',
    stats: [
      { value: 'Unique', label: 'Paiement' },
      { value: 'Pro', label: 'Acces' },
      { value: 'CMI', label: 'Carte' },
    ],
    paymentMethods: [
      { value: 'cmi', label: 'CMI', description: 'Carte bancaire' },
      { value: 'bank_transfer', label: 'Virement', description: 'Validation finance' },
      { value: 'cashplus', label: 'CashPlus', description: 'Paiement agence' },
      { value: 'ashplus', label: 'AshPlus', description: 'Paiement agence' },
    ],
    freeFeatures: [
      'Acces aux lecons en apercu',
      'Suivi de progression basique',
      'Discussions communautaires',
      '3 matieres disponibles',
    ],
    proFeatures: [
      'Toutes les lecons et chapitres debloques',
      'Suivi complet de progression et serie',
      'Quiz interactifs avec correction',
      'Certificats de completion',
      'Support prioritaire',
      'Nouveau contenu chaque semaine',
    ],
  },
} as const
