export const DEFAULT_LOCALE = 'fr-MA'

export const localizedCopy = {
  auth: {
    welcome: 'Bienvenue sur Kresco',
    loginToAccess: 'Connectez-vous pour accéder à vos cours du Bac.',
    continueWithGoogle: 'Continuer avec Google',
    facebookComingSoon: 'Facebook (bientôt)',
    appleComingSoon: 'Apple (bientôt)',
    loginLoading: 'Connexion...',
    createAccount: 'Créer un compte',
    alreadyHaveAccount: 'Déjà un compte ?',
    loginAction: 'Se connecter',
    signUpTitle: 'Sign up',
    joinFree: 'Rejoignez Kresco gratuitement.',
    fullName: 'Nom complet',
    fullNamePlaceholder: 'Ahmed Benali',
    email: 'Email',
    emailPlaceholder: 'vous@exemple.com',
    password: 'Mot de passe',
    passwordMinPlaceholder: 'Min. 6 caracteres',
    passwordPlaceholder: 'Votre mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    createAccountAction: 'Créer mon compte',
    creating: 'Création...',
    noAccountYet: 'Pas encore de compte ?',
    verifyEmailTitle: 'Vérifiez votre email',
    verifyEmailBody1: 'Nous avons envoyé un lien à',
    verifyEmailBody2: 'Cliquez dessus pour activer votre compte.',
    resendEmail: "Renvoyer l'email",
    resending: 'Envoi...',
    backToHome: "Retour à l'accueil",
    logInTitle: 'Log in',
    welcomeBack: 'Content de vous revoir !',
    forgotPassword: 'Mot de passe oublié ?',
    forgotPasswordTitle: 'Mot de passe oublié',
    forgotPasswordBody: 'Entrez votre email, nous vous enverrons un lien de réinitialisation.',
    sendLink: 'Envoyer le lien',
    backToLogin: 'Retour à la connexion',
    emailSentTitle: 'Email envoyé !',
    emailSentBody: 'Si un compte existe avec cette adresse, vous recevrez un lien sous peu.',
    whatLevel: 'Quel est votre niveau ?',
    helpsUsPersonalize: 'Cela nous aide à personnaliser votre expérience.',
    continueBtn: 'Continuer',
    whatSpecialty: 'Quelle est votre filière ?',
    selectSpecialty: 'Sélectionnez votre spécialité du Bac.',
    start: 'Commencer',
    saving: 'Sauvegarde...',
    google: 'Google',
    facebook: 'Facebook',
    apple: 'Apple',
    resetPasswordInvalidLinkTitle: 'Lien invalide',
    resetPasswordInvalidLinkBody: 'Ce lien de réinitialisation est invalide ou a expiré.',
    resetPasswordSuccessTitle: 'Mot de passe mis à jour !',
    resetPasswordSuccessBody: 'Redirection vers la connexion...',
    resetPasswordTitle: 'Nouveau mot de passe',
    resetPasswordBody: 'Choisissez un mot de passe sécurisé pour votre compte.',
    resetPasswordConfirmLabel: 'Confirmer le mot de passe',
    resetPasswordSaveBtn: 'Enregistrer le mot de passe',
    resetPasswordMismatch: 'Les mots de passe ne correspondent pas',
    verifyEmailVerifiedTitle: 'Email vérifié !',
    verifyEmailVerifiedBody: 'Votre adresse a été confirmée avec succès.',
    verifyEmailInvalidTitle: 'Lien invalide',
    verifyEmailInvalidBody: 'Ce lien de vérification est invalide ou a expiré.',
    professorLoginTitle: 'Espace Professeur',
    professorLoginBody: 'Connectez-vous pour gérer vos cours et interagir avec les élèves.',
    professorLoginAction: 'Connexion Professeur'
  },

  pricing: {
    backHome: "Retour a l'accueil",
    badge: 'Ameliorez votre apprentissage',
    title: 'Tarification simple et transparente',
    subtitle: 'Un paiement unique pour debloquer Kresco Pro.',
    freePlan: 'Gratuit',
    freePrice: '0 MAD',
    freeDescription: 'Commencez avec les lecons en apercu.',
    previousPlan: 'Plan precedent',
    currentPlan: 'Plan actuel',
    proPlan: 'Pro',
    popular: 'Le plus populaire',
    proPrice: '99 MAD',
    oneTime: 'une fois',
    stripeActivation: 'Acces Pro active apres confirmation Stripe.',
    proDescription: "Tout ce qu'il faut pour reussir votre Bac.",
    proActive: 'Vous etes Pro !',
    checkout: "Acheter l'acces Pro - 99 MAD",
    securePayment: 'Paiement unique securise via Stripe',
    stats: [
      { value: 'Unique', label: 'Paiement' },
      { value: 'Pro', label: 'Acces' },
      { value: 'Stripe', label: 'Checkout' },
    ],
    freeFeatures: [
      'Acces aux lecons en apercu',
      'Suivi de progression basique',
      'Discussions communautaires',
      '3 matieres disponibles',
    ],
    proFeatures: [
      'Toutes les lecons et chapitres debloques',
      'Suivi complet de progression et serie',
      'Quiz interactifs avec correction',
      'Certificats de completion',
      'Support prioritaire',
      'Nouveau contenu chaque semaine',
    ],
  },
} as const
